/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wuhaowen_encrypt_SignatureEncryptor */

#ifndef _Included_com_wuhaowen_encrypt_SignatureEncryptor
#define _Included_com_wuhaowen_encrypt_SignatureEncryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wuhaowen_encrypt_SignatureEncryptor
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wuhaowen_encrypt_SignatureEncryptor_encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_wuhaowen_encrypt_SignatureEncryptor
 * Method:    encryptWithoutSecurekey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wuhaowen_encrypt_SignatureEncryptor_encryptWithoutSecurekey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
